spring:
  cloud:
    config:
      server:
        composite:
          - type: git
            uri: ${CONFIG_REPO_URI}
            search-paths: config
            default-label: ${CONFIG_REPO_BRANCH:main}
          - type: vault
            host: ${VAULT_HOST}
            port: 8200
            scheme: http
            authentication: AWS_IAM
            aws-iam:
              role: ${VAULT_AWS_ROLE}
            kv-version: 2
            backend: secret
            default-key: petadoption/services
